# Generated by Django 4.1.1 on 2022-09-22 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menbers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='adresse',
            new_name='address',
        ),
    ]
